# Generated by Django 3.1.7 on 2021-03-25 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField(blank=True, verbose_name='repository_url')),
                ('users', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('text', models.TextField(max_length=512)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='create_at')),
                ('date_update', models.DateTimeField(auto_now_add=True, verbose_name='update_at')),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='note.project')),
            ],
        ),
    ]
