# Generated by Django 3.1.7 on 2021-03-12 22:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20210312_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField(verbose_name='ссылка на репозиторий')),
                ('user', models.ManyToManyField(to='user.NoteUser')),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=512)),
                ('date_create', models.DateTimeField(default=datetime.datetime(2021, 3, 12, 22, 15, 55, 691251), verbose_name='время создания')),
                ('date_update', models.DateTimeField(default=datetime.datetime(2021, 3, 12, 22, 15, 55, 691285), verbose_name='время обновления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.noteuser')),
            ],
        ),
    ]
