# Generated by Django 3.1.7 on 2021-03-12 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime, verbose_name='время обновления'),
        ),
    ]
