# Generated by Django 3.1.7 on 2021-03-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20210312_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время обновления'),
        ),
    ]
