# Generated by Django 3.1.7 on 2021-03-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20210313_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
    ]
