# Generated by Django 3.1.7 on 2021-03-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_auto_20210313_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='project',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='username',
        ),
    ]
