# Generated by Django 3.1.7 on 2021-03-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210312_2203'),
        ('note', '0012_auto_20210319_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='username',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='project_name',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='username',
        ),
        migrations.AddField(
            model_name='todo',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='user', to='user.noteuser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, verbose_name='repository_url'),
        ),
    ]
