# Generated by Django 3.1.7 on 2021-04-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteuser',
            options={'verbose_name': 'User'},
        ),
    ]
